### ISSUE TITLE
Warm me, but let me be the judge

### ISSUE THREAD

**Issue by Fastidious** [kaepora/miniLock#181]
I am trying to use my brand new miniLock. I am typing a password in the form:

`&^%2015Ilovethebrownlazydog.`

It keeps telling me it is too weak, and recommending I use one the program is generating for me. I want to use mine, but I can't, nor I can proceed unless I pick a different one, or use one of the recommended.

It is great to recommend, and explain why, but do not make it a show stopper. If I want to foolishly pick a weaker password, I should be allowed.

**Comment by RainaBatwing** [comment]
Could you use a regular zip file instead of miniLock? The purpose of miniLock is to provide some genuine privacy. If your passphrase doesn't have enough entropy miniLock wont work and it becomes an overcomplicated less useful zip file.

One of the reasons for requiring users to have strong passphrases even the first time they play with miniLock is that users can publish their miniLockID on twitter or the web or business cards or a text message and things like that. We made the miniLockID compact and friendly so this would be easy. But if someone plays with it like a toy with a bad passphrase, shares their toy miniLockID, they could get stuck using an ID that isn't secure at all, that would be a very bad experience and potentially dangerous. Instead of feeling protected by miniLock they could feel betrayed by it for letting them get trapped in a bad situation. The miniLockID is derived from the passphrase, so there is no way to change your passphrase but keep the same miniLockID. Changing your passphrase is about as complicated as changing a telephone number. You have to tell everyone you want to contact you that it's changed now. Better to get it right from the start.

**Comment by Fastidious** [comment]
@RainaBatwing You write as if I did not know what miniLock was or how it worked. I do.

GPG provides genuine privacy, why will I need or want miniLock? For the convenience of a shorter public key. Considering the many open issues miniLock has, and the lack of activity--which leads me to believe it is a dying project--I think I will stick with GPG 2.1.2+, which has support for ECDH.

**Comment by RainaBatwing** [comment]
miniLock is not a dying project. miniLock is a core technology in the peer.io startup @kaepora is working on, as well as being ported to other languages. The desktop app is mostly finished. It could benefit from localisation for example. When the purpose is to be simple, and all the features are implemented, there's no need to commit anymore or change anything. Finished is not the same as dead or unmaintained.

I agree that the passphrases are annoying. If you would like to use miniLock encryption with something a bit more managed, peer.io maybe interesting to you. It handles identity and cloud communications.

Talking about GPG, it sounds like you're happy with it. If the people you share private messages with are also happy with GPG, there's no reason to change. Please try to understand that not everything is for you, and when a piece of software isn't built with you as the primary user in mind, that isn't an issue that needs resolution! One of @kaepora's goals with their projects have been to make apps for people who aren't technical, not to just make more apps for people who already have plenty of options. He's really good at it - another of his apps CryptoCat is used by many activists and has been used by journalists to organise leaks in the public interest.

miniLock is good for another type of person who finds GPG complicated or confusing and often doesn't bother encrypting because of this complexity. Imagine for instance some uni students are organising a protest. The last few protests were met with police already there when they arrived to start, and are quickly shut down. Somehow the police already knew where the protest would be ahead of time. miniLock gives them an easy, friendly way to trade documents like poster designs without anyone unintended who might snoop on their emails or facebook messages from being able to open them and see the location and time ahead of it's official release.

Imagine a journalist is offering a way for people to leak documents to them. A public project has some corruption, and an office worker has stumbled on documents which expose this. The journalist can recommend miniLock, which will do it's best to help this office worker who maybe great at word and excel, but would be scared off by a terminal, and isn't savvy enough to feel comfortable installing random apps with spyware concerns. They could load miniLock in their browser and encrypt the secret documents for transmission. Because miniLock doesn't leave any keys or settings around, if their employer later tried to find out who did the leaking, it would be more difficult.

Why should anyone care about you not wanting to be secure when you use miniLock? Your issue is very strange.

**Comment by Fastidious** [comment]
Thanks for the lead to peerio.com (not peer.io), interesting. Cheers!
